# Generated by Django 5.2.6 on 2025-09-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_fabricante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_referencia', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=1)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
